version: 2

models:
  - name: dim_superstore_customer
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null
          
      - name: customerid
        tests:
          - not_null
      
      - name: customername
        tests:
          - not_null


  - name: dim_superstore_products
    columns:
      - name: product_sk
        tests:
          - unique
          - not_null
          
      - name: productid
        tests:
          - not_null
          
      - name: category
        tests:
          - not_null

  - name: fact_superstore
    columns:
      - name: customer_sk
        tests:
          - relationships:
              arguments: 
                to: ref('dim_superstore_customer')
                field: customer_sk

      - name: product_sk
        tests:
          - relationships:
              arguments: 
                to: ref('dim_superstore_products')
                field: product_sk

      - name: orderid
        tests:
          - not_null
      
      - name: sales
        tests:
          - not_null
          
          