version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null
      
      - name: customerid
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_sk
        tests:
          - unique
          - not_null
  - name: fact_orders
    columns:
      - name: customer_sk
        tests:
          - relationships:
              field: customer_sk
              to: ref('dim_customer')

      - name: product_sk
        tests:
          - relationships:
              field: product_sk
              to: ref('dim_products')