version: 2

models:
  - name: dim_gemini_customers
    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null
      
      - name: customer_id
        tests:
          - not_null

  - name: dim_gemini_products
    columns:
      - name: product_sk
        tests:
          - unique
          
  - name: facts_gemini_sales
    columns:
      - name: customer_sk
        tests:
          - relationships:
              arguments: 
                to: ref('dim_gemini_customers')
                field: customer_sk


      - name: product_sk
        tests:
          - relationships:
              arguments: 

                to: ref('dim_gemini_products')
                field: product_sk